[package]
name = "caskdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc = "3.0.1"
tempfile = "3.4.0"
time = "0.3.20"
time-macros = "0.2.8"

